services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: budget-backend
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/budget_planner
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Riteshsai*123
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: budget-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: budget-db
    restart: always
    environment:
      MYSQL_DATABASE: budget_planner
      MYSQL_ROOT_PASSWORD: Riteshsai*123
    volumes:
      - db_data:/var/lib/mysql
    # Option A: Keep it internal only (no conflicts)
    # ports: []
    
    # Option B: Uncomment if you want external access on localhost:3307
    ports:
      - "3307:3306"

volumes:
  db_data:
